

CREATE ROLE postgres1 LOGIN PASSWORD 'postgres1';


CREATE DATABASE uglygoldwood TEMPLATE template1;
GRANT ALL PRIVILEGES ON DATABASE uglygoldwood TO postgres1;


CREATE TABLESPACE dvm64 LOCATION '/var/db/postgres1/dvm64';
CREATE TABLESPACE hmd60 LOCATION '/var/db/postgres1/hmd60';
CREATE TABLESPACE iqp71 LOCATION '/var/db/postgres1/iqp71';


GRANT ALL PRIVILEGES ON TABLESPACE dvm64 TO postgres1;
GRANT ALL PRIVILEGES ON TABLESPACE hmd60 TO postgres1;
GRANT ALL PRIVILEGES ON TABLESPACE iqp71 TO postgres1;